// const config = {
//   showEmployee: "http://localhost:3000/employee/list",
//   showEmployeefiltered: "http://localhost:3000/employee/list/filtered",
//   showTypes: "http://localhost:3000/employee/types",
//   showPos: "http://localhost:3000/employee/positions",
//   showRates: "http://localhost:3000/employee/rates",
//   showSched: "http://localhost:3000/employee/schedule",
//   addTypes: "http://localhost:3000/employee/types/add",
//   addPosition: "http://localhost:3000/employee/positions/add",
//   addRate: "http://localhost:3000/employee/rates/add",
//   addSchedule: "http://localhost:3000/employee/schedule/add",
//   addEmployee: "http://localhost:3000/employee/add",
//   removeDropdown: "http://localhost:3000/employee/items/remove",
//   editEmployee: "http://localhost:3000/employee/update",
//   removeEmployee: "http://localhost:3000/employee/remove",
//   showAttendance: "http://localhost:3000/attendance",
//   filteredAttendance: "http://localhost:3000/attendance/filtered",
//   employeeRequest: "http://localhost:3000/employee/request",
//   updateRequest: "http://localhost:3000/employee/request/update",
//   timesheetEmployee: "http://localhost:3000/employee/timesheet",
//   timesheetEmployeeFiltered:
//     "http://localhost:3000/employee/timesheet/filtered",
//   timesheetDetails: "http://localhost:3000/employee/timesheet/details",
//   holidays: "http://localhost:3000/holidays",
//   payroll: "http://localhost:3000/payroll/employee/details",
//   payrollAdjustment: "http://localhost:3000/payroll/employee/adjustment",
//   showPayrollAdjustment:
//     "http://localhost:3000/payroll/employee/show/adjustment",
//   payrollDeleteAdjustment:
//     "http://localhost:3000/payroll/employee/delete/adjustment",
//   showContributions: "http://localhost:3000/payroll/contributions",
//   updateContributions: "http://localhost:3000/payroll/contributions/update",
//   getContribution: "http://localhost:3000/payroll/contributions/show",
//   addPayroll: "http://localhost:3000/make/payroll",
//   payrollLogs: "http://localhost:3000/payroll/logs",
//   payrollEmployee: "http://localhost:3000/payroll/list",
//   payrollCutoffLogs: "http://localhost:3000/payroll/cutoff/logs",
//   deleteCutoff: "http://localhost:3000/payroll/cutoff/delete",
//   requesthistory: "http://localhost:3000/employee/request/history",
//   dashboardDetails: "http://localhost:3000/dashboard",
//   updateAttendance: "http://localhost:3000/attendance/update",
//   showLeavetypes: "http://localhost:3000/employee/leavetypes",
//   addLeaveTypes: "http://localhost:3000/employee/leavetypes/add",
//   changeEmployeePass: "http://localhost:3000/mobile/forgotpass/new",
//   employeeInfo: "http://localhost:3000/employee/information",
//   login: "http://localhost:3000/payroll/login",
// };

const config = {
  showEmployee: "https://server-ywyf.onrender.com/employee/list",
  showEmployeefiltered:
    "https://server-ywyf.onrender.com/employee/list/filtered",
  showTypes: "https://server-ywyf.onrender.com/employee/types",
  showPos: "https://server-ywyf.onrender.com/employee/positions",
  showRates: "https://server-ywyf.onrender.com/employee/rates",
  showSched: "https://server-ywyf.onrender.com/employee/schedule",
  addTypes: "https://server-ywyf.onrender.com/employee/types/add",
  addPosition: "https://server-ywyf.onrender.com/employee/positions/add",
  addRate: "https://server-ywyf.onrender.com/employee/rates/add",
  addSchedule: "https://server-ywyf.onrender.com/employee/schedule/add",
  addEmployee: "https://server-ywyf.onrender.com/employee/add",
  removeDropdown: "https://server-ywyf.onrender.com/employee/items/remove",
  editEmployee: "https://server-ywyf.onrender.com/employee/update",
  removeEmployee: "https://server-ywyf.onrender.com/employee/remove",
  showAttendance: "https://server-ywyf.onrender.com/attendance",
  filteredAttendance: "https://server-ywyf.onrender.com/attendance/filtered",
  employeeRequest: "https://server-ywyf.onrender.com/employee/request",
  updateRequest: "https://server-ywyf.onrender.com/employee/request/update",
  timesheetEmployee: "https://server-ywyf.onrender.com/employee/timesheet",
  timesheetEmployeeFiltered:
    "https://server-ywyf.onrender.com/employee/timesheet/filtered",
  timesheetDetails:
    "https://server-ywyf.onrender.com/employee/timesheet/details",
  holidays: "https://server-ywyf.onrender.com/holidays",
  payroll: "https://server-ywyf.onrender.com/payroll/employee/details",
  payrollAdjustment:
    "https://server-ywyf.onrender.com/payroll/employee/adjustment",
  showPayrollAdjustment:
    "https://server-ywyf.onrender.com/payroll/employee/show/adjustment",
  payrollDeleteAdjustment:
    "https://server-ywyf.onrender.com/payroll/employee/delete/adjustment",
  showContributions: "https://server-ywyf.onrender.com/payroll/contributions",
  updateContributions:
    "https://server-ywyf.onrender.com/payroll/contributions/update",
  getContribution:
    "https://server-ywyf.onrender.com/payroll/contributions/show",
  addPayroll: "https://server-ywyf.onrender.com/make/payroll",
  payrollLogs: "https://server-ywyf.onrender.com/payroll/logs",
  payrollEmployee: "https://server-ywyf.onrender.com/payroll/list",
  payrollCutoffLogs: "https://server-ywyf.onrender.com/payroll/cutoff/logs",
  deleteCutoff: "https://server-ywyf.onrender.com/payroll/cutoff/delete",
  requesthistory: "https://server-ywyf.onrender.com/employee/request/history",
  dashboardDetails: "https://server-ywyf.onrender.com/dashboard",
  updateAttendance: "https://server-ywyf.onrender.com/attendance/update",
  showLeavetypes: "https://server-ywyf.onrender.com/employee/leavetypes",
  addLeaveTypes: "https://server-ywyf.onrender.com/employee/leavetypes/add",
  changeEmployeePass: "https://server-ywyf.onrender.com/mobile/forgotpass/new",
  employeeInfo: "https://server-ywyf.onrender.com/employee/information",
  login: "https://server-ywyf.onrender.com/payroll/login",
};

export default config;
